# Generated by Django 4.0.4 on 2022-04-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='camada',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
