# Generated by Django 4.0.4 on 2022-05-29 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_remove_jugadora_deporte'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Torneo',
        ),
    ]
