# Generated by Django 4.0.4 on 2022-04-22 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_rename_cursos_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='duracion',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='mail',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
