# Generated by Django 4.0.4 on 2022-05-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0007_club_delete_curso_delete_entregable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('mail', models.EmailField(default='', max_length=254)),
                ('club', models.CharField(max_length=30)),
                ('deporte', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
    ]
