# Generated by Django 4.0.4 on 2022-05-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0008_jugadora_delete_estudiante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('deporte', models.CharField(max_length=30)),
                ('duracion', models.IntegerField()),
            ],
        ),
    ]
